drinks/urls.py
from django.urls import path
from drinks.views import *
app_name='drinks'
urlpatterns=[
    path('mazza/',mazza,name='mazza'),
    path('sprit/',sprit,name='sprit'),
]

food/urls.py
from django.urls import path
from food.views import *
app_name='food'
urlpatterns=[
    path('biryani/',biryani,name='biryani'),
    path('parota/',parota,name='parota'),
]

project17/urls.py
from django.contrib import admin
from django.urls import path,include
import food,drinks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('drinks/',include('drinks.urls')),
]

drinks/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

drinks/views.py
from django.shortcuts import render

# Create your views here.
def mazza(request):
    return render(request,'mazza.html')
def sprit(request):
    return render(request,'sprit.html')

food/views.py
from django.shortcuts import render

# Create your views here.
def biryani(request):
    return render(request,'biryani.html')
def parota(request):
    return render(request,'parota.html')

templates/biryani.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            this is the special item biryani
            <h1><a href="{% url 'drinks:sprit' %}">shift to  drinks section</a></h1>
            <h1><a href="{% url 'food:parota' %}">shift to food section</a></h1>
            <h1><a href="{% url 'drinks:mazza' %}">shift to mazza juice</a></h1>
            <img src="{% static 'images/biryani.jpeg' %}" alt="image not found">
        </h1>
    </center>
</body>
</html>

templates/mazza.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is the mazza drinks section</h1>
            <h1><a href="{% url 'food:biryani' %}">shift to food section</a></h1>
           <h1><a href="{% url 'food:parota' %}">shift to food section</a></h1>
           <h1> <a href="{% url 'drinks:sprit' %}">shift to sprit juice</a></h1>
           <img src="{% static 'images/mazza.jpeg' %}" alt="image not found">
    </center>
</body>
</html>

templates/parota.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            this is the parota section
            <h1><a href="{% url 'food:biryani' %}">shift to food section</a></h1>
            <h1><a href="{% url 'drinks:sprit' %}">shift to juice  section</a></h1>
            <h1><a href="{% url 'drinks:mazza' %}">shift to mazza juice</a></h1>
            <img src="{% static 'images/parota.jpeg' %}" alt="image not found">
            
        </h1>
    </center>
</body>
</html>

templates/sprit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            this is also a drinks section i.e sprit juice
            <h1><a href="{% url 'food:biryani' %}">shift to food section</a></h1>
            <h1><a href="{% url 'food:parota' %}">shift to food section</a></h1>
            <h1><a href="{% url 'drinks:mazza' %}">shift to mazza juice</a></h1>
        </h1>
        <img src="{% static 'images/sprit.jpeg' %}" alt="image not found">
    </center>
    
</body>
</html>